name: Ansible CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Show versions
        run: |
          ansible --version
          python3 --version

      - name: Run playbook (localhost)
        run: ansible-playbook -i inventory playbooks/hello.yml
